In [30]:
import pandas as pd
import numpy as np
#example of series in pandas
data=np.array (['a','b','c','d'])
s=pd.Series(data,index=[0,1,2,3])
print(s)

0    a
1    b
2    c
3    d
dtype: object

In [31]:
#example of dataframe
data1=[1,2,3,4,5]
df=pd.DataFrame(data1)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [32]:
#2nd example
data2=[['Alex',10],['Bob',12],['Clark',13]]
df1=pd.DataFrame(data2,columns=['Name','Age'])
print (df1)

    Name  Age
0   Alex   10
1    Bob   12
2  Clark   13

In [28]:
#3rd example
data3={'Name':['tom','jack','steve','ricky'],'Age':[28,34,29,42]}
df2=pd.DataFrame(data3)
print (df2)

    Name  Age
0    tom   28
1   jack   34
2  steve   29
3  ricky   42

In [29]:
#4th example
data4=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df3=pd.DataFrame(data4)
print(df3)

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [1]:
# reading data from csv file pending
import pandas as pd
df5= pd.read_csv("C:\\Users\\vedan\\Downloads\\datasets\\cars.csv")
print (df5)

           Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [3]:
#2.for reading a specific block or column from csv file
print(df5['Volume'])

0     1000
1     1200
2     1000
3      900
4     1500
5     1000
6     1400
7     1500
8     1500
9     1600
10    1100
11    1300
12    1000
13    1600
14    1600
15    1600
16    1600
17    2200
18    1600
19    2000
20    1600
21    2000
22    2100
23    1600
24    2000
25    1500
26    2000
27    2000
28    1600
29    2000
30    2100
31    2000
32    1600
33    1600
34    1600
35    2500
Name: Volume, dtype: int64

In [4]:
#3 addition of a practicular block
sum(df5['Volume'])

58000

In [5]:
#4 reading data from 2 columns
print(df5[['Model','CO2']])

         Model  CO2
0         Aygo   99
1   Space Star   95
2       Citigo   95
3          500   90
4       Cooper  105
5          Up!  105
6        Fabia   90
7      A-Class   92
8       Fiesta   98
9           A1   99
10         I20   99
11       Swift  101
12      Fiesta   99
13       Civic   94
14         I30   97
15       Astra   97
16           1   99
17           3  104
18       Rapid  104
19       Focus  105
20      Mondeo   94
21    Insignia   99
22     C-Class   99
23     Octavia   99
24         S60   99
25         CLA  102
26          A4  104
27          A6  114
28         V70  109
29           5  114
30     E-Class  115
31        XC70  117
32       B-Max  104
33         216  108
34      Zafira  109
35         SLK  120

In [6]:
#5 generating one random row 
print(df5.sample(n=1))
print(df5.shape)

     Car  Model  Volume  Weight  CO2
6  Skoda  Fabia    1400    1109   90
(36, 5)

In [16]:
#6 adding a new column at dataset
No_of_Delivery=[2,3,4,5,3,4,3,2,5,6,2,2,3,3,4,5,5,6,5,0,2,2,2,3,2,3,2,3,2,3,2,3,5,1,2,4]
df5['Delivery_No']=No_of_Delivery

In [15]:
df=pd.read_csv("C:\\Users\\vedan\\Downloads\\datasets\\cars.csv")
print(df)

           Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [17]:
#7 deleting a column from dataset
del df5['Delivery_No']

In [18]:
#8 checking first 5 elements
df.head()

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [19]:
#9 checking last 5 elements 
df.tail()

         Car   Model  Volume  Weight  CO2
31     Volvo    XC70    2000    1746  117
32      Ford   B-Max    1600    1235  104
33       BMW     216    1600    1390  108
34      Opel  Zafira    1600    1405  109
35  Mercedes     SLK    2500    1395  120

In [ ]:
#10 from reading initial from dataframe
df.head(10) # 1st excuted this
df.tail(7)  # 2nd this

         Car    Model  Volume  Weight  CO2
29       BMW        5    2000    1705  114
30  Mercedes  E-Class    2100    1605  115
31     Volvo     XC70    2000    1746  117
32      Ford    B-Max    1600    1235  104
33       BMW      216    1600    1390  108
34      Opel   Zafira    1600    1405  109
35  Mercedes      SLK    2500    1395  120

In [25]:
#11 for checking initial rows under any column 
df['Car'].head()
df['Model'].head()
df['Volume'].head()

0    1000
1    1200
2    1000
3     900
4    1500
Name: Volume, dtype: int64

In [26]:
#12 sorting data frame based on a column 
df.sort_values("Volume")

           Car       Model  Volume  Weight  CO2
3         Fiat         500     900     865   90
0       Toyoty        Aygo    1000     790   99
2        Skoda      Citigo    1000     929   95
5           VW         Up!    1000     929  105
12        Ford      Fiesta    1000    1112   99
10     Hyundai         I20    1100     980   99
1   Mitsubishi  Space Star    1200    1160   95
11      Suzuki       Swift    1300     990  101
6        Skoda       Fabia    1400    1109   90
4         Mini      Cooper    1500    1140  105
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
25    Mercedes         CLA    1500    1465  102
9         Audi          A1    1600    1150   99
14      Hundai         I30    1600    1326   97
13       Honda       Civic    1600    1252   94
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
23       Skoda     Octavia    1600    1415   99
18       Skoda       Rapid    1600    1119  104
28       Volvo         V70    1600    1523  109
20        Ford      Mondeo    1600    1584   94
33         BMW         216    1600    1390  108
32        Ford       B-Max    1600    1235  104
34        Opel      Zafira    1600    1405  109
27        Audi          A6    2000    1725  114
26        Audi          A4    2000    1490  104
24       Volvo         S60    2000    1415   99
31       Volvo        XC70    2000    1746  117
29         BMW           5    2000    1705  114
21        Opel    Insignia    2000    1428   99
19        Ford       Focus    2000    1328  105
22    Mercedes     C-Class    2100    1365   99
30    Mercedes     E-Class    2100    1605  115
17       Mazda           3    2200    1280  104
35    Mercedes         SLK    2500    1395  120

In [27]:
df.sort_values("Volume",ascending=False)

           Car       Model  Volume  Weight  CO2
35    Mercedes         SLK    2500    1395  120
17       Mazda           3    2200    1280  104
30    Mercedes     E-Class    2100    1605  115
22    Mercedes     C-Class    2100    1365   99
24       Volvo         S60    2000    1415   99
26        Audi          A4    2000    1490  104
29         BMW           5    2000    1705  114
27        Audi          A6    2000    1725  114
21        Opel    Insignia    2000    1428   99
19        Ford       Focus    2000    1328  105
31       Volvo        XC70    2000    1746  117
23       Skoda     Octavia    1600    1415   99
16         BMW           1    1600    1365   99
28       Volvo         V70    1600    1523  109
20        Ford      Mondeo    1600    1584   94
9         Audi          A1    1600    1150   99
14      Hundai         I30    1600    1326   97
13       Honda       Civic    1600    1252   94
15        Opel       Astra    1600    1330   97
18       Skoda       Rapid    1600    1119  104
33         BMW         216    1600    1390  108
32        Ford       B-Max    1600    1235  104
34        Opel      Zafira    1600    1405  109
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
4         Mini      Cooper    1500    1140  105
25    Mercedes         CLA    1500    1465  102
6        Skoda       Fabia    1400    1109   90
11      Suzuki       Swift    1300     990  101
1   Mitsubishi  Space Star    1200    1160   95
10     Hyundai         I20    1100     980   99
0       Toyoty        Aygo    1000     790   99
12        Ford      Fiesta    1000    1112   99
2        Skoda      Citigo    1000     929   95
5           VW         Up!    1000     929  105
3         Fiat         500     900     865   90

In [28]:
#13 count no. of unique valiues in dataset or in a column
df.nunique

<bound method DataFrame.nunique of            Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120>

In [31]:
#14 for addition or sum of column
sum(df['Weight'])
#sum(df['Volume'])

46522

In [32]:
#indexing using labels in pandas
"pandas.dataframe.loc"

'pandas.dataframe.loc'

In [33]:
#1 selecting rows from 1st to 4th 
df.loc[1:4]

          Car       Model  Volume  Weight  CO2
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [34]:
#2 print 1st five rows including 5th index and every column of df
df.loc[0:5,:]

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105
5          VW         Up!    1000     929  105

In [35]:
#3 print from 5th row onwards and entire column 
df.loc[5:,:]

         Car     Model  Volume  Weight  CO2
5         VW       Up!    1000     929  105
6      Skoda     Fabia    1400    1109   90
7   Mercedes   A-Class    1500    1365   92
8       Ford    Fiesta    1500    1112   98
9       Audi        A1    1600    1150   99
10   Hyundai       I20    1100     980   99
11    Suzuki     Swift    1300     990  101
12      Ford    Fiesta    1000    1112   99
13     Honda     Civic    1600    1252   94
14    Hundai       I30    1600    1326   97
15      Opel     Astra    1600    1330   97
16       BMW         1    1600    1365   99
17     Mazda         3    2200    1280  104
18     Skoda     Rapid    1600    1119  104
19      Ford     Focus    2000    1328  105
20      Ford    Mondeo    1600    1584   94
21      Opel  Insignia    2000    1428   99
22  Mercedes   C-Class    2100    1365   99
23     Skoda   Octavia    1600    1415   99
24     Volvo       S60    2000    1415   99
25  Mercedes       CLA    1500    1465  102
26      Audi        A4    2000    1490  104
27      Audi        A6    2000    1725  114
28     Volvo       V70    1600    1523  109
29       BMW         5    2000    1705  114
30  Mercedes   E-Class    2100    1605  115
31     Volvo      XC70    2000    1746  117
32      Ford     B-Max    1600    1235  104
33       BMW       216    1600    1390  108
34      Opel    Zafira    1600    1405  109
35  Mercedes       SLK    2500    1395  120

In [36]:
#4 compute various summary statistcs 
df.describe()

            Volume       Weight         CO2
count    36.000000    36.000000   36.000000
mean   1611.111111  1292.277778  102.027778
std     388.975047   242.123889    7.454571
min     900.000000   790.000000   90.000000
25%    1475.000000  1117.250000   97.750000
50%    1600.000000  1329.000000   99.000000
75%    2000.000000  1418.250000  105.000000
max    2500.000000  1746.000000  120.000000

In [37]:
#5 filtering under 1 condition 
# select all rows qith a condition 
df['CO2']>=95
# reading a data from co2 greater than 95

0      True
1      True
2      True
3     False
4      True
5      True
6     False
7     False
8      True
9      True
10     True
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18     True
19     True
20    False
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
Name: CO2, dtype: bool

In [38]:
#6getting output in run showing not in condition form
df[df['CO2']>=95]

           Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [39]:
#7 iloc select specific colum with specific index
df.iloc[[0,2]]

      Car   Model  Volume  Weight  CO2
0  Toyoty    Aygo    1000     790   99
2   Skoda  Citigo    1000     929   95

In [40]:
#8 select rows with particular indices and parricular columns
df.iloc[[0,3,4,7,2,5,8,10],[1,2]]

      Model  Volume
0      Aygo    1000
3       500     900
4    Cooper    1500
7   A-Class    1500
2    Citigo    1000
5       Up!    1000
8    Fiesta    1500
10      I20    1100